env: release
port: 8081
dataSource:
  # type: mysql postgres sqlite
  type: mysql
  username: root
  password: qwert12345
  host: 47.99.180.88
  port: 3306
  database: ginchat

dataSourcePool:
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

mail:
  host: smtp.163.com
  username: new001code@163.com
  fromName: new001
  password: LELAZIGQPJIDULFQ
  port: 25
  poolSize: 4

redis:
  host: 47.99.180.88
  port: 6379
  password: qwert12345
  db: 0
