env: release
port: 8081
dataSource:
  # type: mysql postgres sqlite
  type: mysql
  username: root
  password: qwert12345
  host: 47.99.180.88
  port: 3306
  database: ginchat

dataSourcePool:
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 86400

mail:
  host: smtp.163.com
  username: 1******.com
  password: 123123213
  protocol: smtps
  port: 465
  default-encoding: UTF-8
