env: release
port: 8081
dataSource:
  # type: mysql postgres sqlite
  type: mysql
  username: root
  password: 12345q
  host: localhost
  port: 3306
  database: ginchat

dataSourcePool:
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

mail:
  host: smtp.163.com
  username: test@163.com
  fromName: test
  password: LELAZIGQPJIDULFQ
  port: 25
  poolSize: 4

redis:
  host: localhost
  port: 6379
  password: qwasda2
  db: 0
